# Generated by Django 6.0.2 on 2026-02-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='播报日期')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('audio_url', models.URLField(blank=True, help_text='外部音频链接（喜马拉雅/网易云/QQ音乐/B站等）', verbose_name='音频链接')),
                ('script_text', models.TextField(blank=True, verbose_name='新闻文稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to=settings.AUTH_USER_MODEL, verbose_name='播报员/上传人')),
            ],
            options={
                'verbose_name': '新闻项目',
                'verbose_name_plural': '新闻项目',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
