# Generated by Django 6.0.2 on 2026-02-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('notice', '通知'), ('urgent', '紧急'), ('activity', '活动'), ('schedule_change', '排班变更')], default='notice', max_length=20, verbose_name='类型')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('target_department', models.CharField(choices=[('all', '全部'), ('broadcast', '广播站'), ('himalaya', '喜马拉雅')], default='all', max_length=20, verbose_name='目标部门')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_announcements', to=settings.AUTH_USER_MODEL, verbose_name='已读用户')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-is_pinned', '-publish_time'],
            },
        ),
    ]
