# Generated by Django 6.0.2 on 2026-02-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchors', models.ManyToManyField(blank=True, related_name='daily_schedules', to=settings.AUTH_USER_MODEL, verbose_name='播音员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '日程安排',
                'verbose_name_plural': '日程安排',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='组名')),
                ('weekday', models.IntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (7, '周日')], unique=True, verbose_name='对应星期')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL, verbose_name='组长')),
                ('members', models.ManyToManyField(blank=True, related_name='broadcast_groups', to=settings.AUTH_USER_MODEL, verbose_name='组员')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节目名称')),
                ('time_slot', models.CharField(max_length=50, verbose_name='时间段')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='schedule.dailyschedule', verbose_name='日程')),
            ],
            options={
                'verbose_name': '节目',
                'verbose_name_plural': '节目',
                'ordering': ['order', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='歌曲名')),
                ('artist', models.CharField(blank=True, max_length=100, verbose_name='歌手')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='schedule.dailyschedule', verbose_name='日程')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['order', 'title'],
            },
        ),
    ]
