# Generated by Django 6.0.2 on 2026-02-08 13:52

from django.db import migrations


def initialize_groups(apps, schema_editor):
    """Initialize 6 groups for weekdays (Monday to Friday, Sunday)"""
    Group = apps.get_model('schedule', 'Group')
    
    groups_data = [
        {'name': '第一组', 'weekday': 1},  # Monday
        {'name': '第二组', 'weekday': 2},  # Tuesday
        {'name': '第三组', 'weekday': 3},  # Wednesday
        {'name': '第四组', 'weekday': 4},  # Thursday
        {'name': '第五组', 'weekday': 5},  # Friday
        {'name': '第六组', 'weekday': 7},  # Sunday
    ]
    
    for group_data in groups_data:
        Group.objects.get_or_create(**group_data)


def remove_groups(apps, schema_editor):
    """Remove initialized groups"""
    Group = apps.get_model('schedule', 'Group')
    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_groups, remove_groups),
    ]
