# Generated by Django 6.0.2 on 2026-02-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiobooking',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('08:00-10:00', '上午 8:00-10:00'), ('10:00-12:00', '上午 10:00-12:00'), ('14:00-16:00', '下午 14:00-16:00'), ('16:00-18:00', '下午 16:00-18:00'), ('19:00-21:00', '晚上 19:00-21:00'), ('21:00-22:00', '晚上 21:00-22:00')], max_length=20, null=True, verbose_name='时间段'),
        ),
    ]
