# Generated by Django 6.0.2 on 2026-02-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_studiobooking_time_slot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studiobooking',
            index=models.Index(fields=['date', 'time_slot', 'status'], name='booking_stu_date_ti_idx'),
        ),
    ]
