# Generated by Django 6.0.2 on 2026-02-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='专辑标题')),
                ('description', models.TextField(blank=True, verbose_name='专辑描述')),
                ('cover_image_url', models.URLField(blank=True, help_text='外部图片链接', verbose_name='封面图链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='音频标题')),
                ('audio_source', models.CharField(choices=[('himalaya', '喜马拉雅'), ('netease', '网易云音乐'), ('qq', 'QQ音乐'), ('bilibili', 'B站'), ('youtube', 'YouTube'), ('other', '其他')], max_length=20, verbose_name='音频来源')),
                ('audio_url', models.URLField(help_text='外部音频链接', verbose_name='音频链接')),
                ('duration', models.CharField(blank=True, help_text='如：05:30', max_length=20, verbose_name='时长')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='himalaya.album', verbose_name='专辑')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_tracks', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '音频轨道',
                'verbose_name_plural': '音频轨道',
                'ordering': ['album', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文稿标题')),
                ('content', models.TextField(verbose_name='文稿内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script', to='himalaya.audiotrack', verbose_name='音频轨道')),
            ],
            options={
                'verbose_name': '文稿',
                'verbose_name_plural': '文稿',
            },
        ),
    ]
