# Generated by Django 6.0.2 on 2026-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, unique=True, verbose_name='模块标识')),
                ('module_label', models.CharField(max_length=100, verbose_name='模块名称')),
                ('allowed_roles', models.JSONField(default=list, help_text='角色列表，如 ["admin", "anchor"]', verbose_name='允许的角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '板块权限',
                'verbose_name_plural': '板块权限',
                'ordering': ['module_name'],
            },
        ),
    ]
