# Generated by Django 6.0.2 on 2026-02-08 13:34

from django.db import migrations


def create_default_permissions(apps, schema_editor):
    """Initialize default ModulePermission data"""
    ModulePermission = apps.get_model('permissions', 'ModulePermission')
    
    default_permissions = [
        {
            'module_name': 'news',
            'module_label': '新闻管理',
            'allowed_roles': ['admin', 'anchor'],
        },
        {
            'module_name': 'schedule',
            'module_label': '节目编排',
            'allowed_roles': ['admin', 'anchor'],
        },
        {
            'module_name': 'booking',
            'module_label': '录音室预约',
            'allowed_roles': ['admin', 'anchor', 'himalaya'],
        },
        {
            'module_name': 'himalaya',
            'module_label': '喜马拉雅管理',
            'allowed_roles': ['admin', 'himalaya'],
        },
        {
            'module_name': 'announcements',
            'module_label': '公告管理',
            'allowed_roles': ['admin'],
        },
        {
            'module_name': 'groups',
            'module_label': '小组管理',
            'allowed_roles': ['admin'],
        },
        {
            'module_name': 'user_management',
            'module_label': '用户管理',
            'allowed_roles': ['admin'],
        },
    ]
    
    for perm_data in default_permissions:
        ModulePermission.objects.get_or_create(
            module_name=perm_data['module_name'],
            defaults={
                'module_label': perm_data['module_label'],
                'allowed_roles': perm_data['allowed_roles'],
                'is_active': True,
            }
        )


def reverse_default_permissions(apps, schema_editor):
    """Remove default permissions"""
    ModulePermission = apps.get_model('permissions', 'ModulePermission')
    module_names = ['news', 'schedule', 'booking', 'himalaya', 'announcements', 'groups', 'user_management']
    ModulePermission.objects.filter(module_name__in=module_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_permissions, reverse_default_permissions),
    ]

